### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeScrollTop' of undefined

### ISSUE THREAD

**Issue by vcraescu** [carlosdcastillo/vim-mode#23]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.13.0-51-generic
**Thrown From**: [vim-mode](https://github.com/carlosdcastillo/vim-mode) package, v0.10.1
### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeScrollTop' of undefined

```
At /home/viorel/.atom/packages/vim-mode/lib/vim-state.coffee:536

TypeError: Cannot read property 'onDidChangeScrollTop' of undefined
  at /home/viorel/.atom/packages/vim-mode/lib/vim-state.coffee:536:35
  at Socket.<anonymous> (/home/viorel/.atom/packages/vim-mode/lib/vim-state.coffee:74:15)
  at Socket.emit (events.js:116:17)
  at readableAddChunk (_stream_readable.js:164:16)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at Pipe.onread (net.js:530:20)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
linter, v0.12.1
vim-mode, v0.10.1

# Dev
No dev packages
```

**Comment by gaving** [comment]
Duplicate of https://github.com/carlosdcastillo/vim-mode/issues/22

**Comment by gaving** [comment]
Sorted in master: https://github.com/carlosdcastillo/vim-mode/issues/22#issuecomment-101057182
