### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by ghost** [carlosdcastillo/vim-mode#25]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Ubuntu 14.04.2
**Thrown From**: [atom-neovim](https://github.com/carlosdcastillo/vim-mode) package, v0.10.1
### Stack Trace

Failed to load the atom-neovim package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/nay/.atom/packages/vim-mode/lib/vim-mode.coffee:4:10)
    at Object.<anonymous> (/home/nay/.atom/packages/vim-mode/lib/vim-mode.coffee:37:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "block-cursor"
    ],
    "themes": [
      "seti-ui",
      "brogrammer-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
autocomplete-php, v0.3.6
brogrammer-syntax, v1.0.0
color-picker, v2.0.4
docblockr, v0.7.2
emmet, v2.3.10
file-icons, v1.5.7
laravel, v0.7.0
linter, v0.12.7
linter-php, v0.0.15
linter-scss-lint, v1.0.4
project-manager, v1.15.10
restore-windows, v0.4.1
seti-ui, v0.7.1
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by EPadronU** [comment]
I also got this error.

[Enter steps to reproduce below:]
1. Execute/run atom

**Atom Version**: 1.1.0-beta1
**System**: "Manjaro Linux"
**Thrown From**: [atom-neovim](https://github.com/carlosdcastillo/vim-mode) package, v0.10.1

### Stack Trace

Failed to load the atom-neovim package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/nodxine/.atom/packages/nvim-mode/lib/vim-mode.coffee:2:37)
    at Object.<anonymous> (/home/nodxine/.atom/packages/nvim-mode/lib/vim-mode.coffee:2:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/home/nodxine/.atom-projects"
  }
}
```

### Installed Packages

``` coffee
# User
keyboard-localization, v1.4.9

# Dev
No dev packages
```

**Comment by rumpelsepp** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: "Arch Linux"
**Thrown From**: [atom-neovim](https://github.com/carlosdcastillo/vim-mode) package, v0.10.1

### Stack Trace

Failed to load the atom-neovim package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/stefan/.atom/packages/nvim-mode/lib/vim-mode.coffee:2:37)
  at Object.<anonymous> (/home/stefan/.atom/packages/nvim-mode/lib/vim-mode.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:725:34)
  at /usr/share/atom/resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.disablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:146:19)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:316:27)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "tasks",
      "vim-mode",
      "atom-neovim",
      "atom-neovim"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.1
file-icons, v1.6.11
keyboard-localization, v1.4.10
language-latex, v0.6.1
minimap, v4.16.0
minimap-git-diff, v4.1.8

# Dev
No dev packages
```

**Comment by caiocutrim** [comment]
you need to enter in the directory and type apm install to install the required dependencies of this project

**Comment by andriy-f** [comment]
Which directory?
