### ISSUE TITLE
I get this error :(

### ISSUE THREAD

**Issue by caiocutrim** [carlosdcastillo/vim-mode#29]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: elementary OS
**Thrown From**: [atom-neovim](https://github.com/carlosdcastillo/vim-mode) package, v0.10.1
### Stack Trace

Uncaught Error: Path must be a string without null bytes.

```
At events.js:141

Error: Path must be a string without null bytes.
    at nullCheck (fs.js:94:14)
    at fs.statSyncNoException (fs.js:858:3)
    at fs.statSyncNoException (ATOM_SHELL_ASAR.js:245:16)
    at Object.fsPlus.getSizeSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:161:24)
    at Project.module.exports.Project.open (/usr/share/atom/resources/app.asar/src/project.js:357:21)
    at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:438:31)
    at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:374:19)
    at /home/caio/.atom/packages/nvim-mode/lib/vim-state.coffee:265:32
    at /home/caio/.atom/packages/nvim-mode/lib/vim-state.coffee:104:25
    at Session._parse_message (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/index.js:96:5)
    at Decoder.<anonymous> (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/index.js:42:11)
    at emitOne (events.js:77:13)
    at Decoder.emit (events.js:169:7)
    at readableAddChunk (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Decoder.Readable.push (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Decoder.Transform.push (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at Decoder.decodeWithoutHeader [as _transform] (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:80:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.Transform._read (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Decoder.Transform._write (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Decoder.Writable.write (/home/caio/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Socket.ondata (_stream_readable.js:521:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:520:20)
```
### Commands

```
     -0:07.8.0 core:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "tool-bar-noderat",
      "tool-bar-besser",
      "tool-bar-config",
      "keyboard-localization",
      "vim-surround",
      "vim-mode-zz",
      "vim-mode",
      "vim-mode-clipboard-plus",
      "ex-mode",
      "nerd-treeview",
      "vim-mode-visual-block"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.5
atom-material-ui, v0.8.0
autocomplete-paths, v1.0.2
browser-plus, v0.0.54
clipboard-plus, v0.5.1
color-picker, v2.0.13
docblockr, v0.7.3
docs-snippets, v0.8.0
inline-messenger, v1.2.8
javascript-snippets, v1.0.0
jsdoc-generator, v0.1.10
make-executable, v0.1.1
nodejs-snippets-extended, v0.0.0
terminal-plus, v0.14.0
time-status, v1.1.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by carlosdcastillo** [comment]
I've pushed some changes to make nvim-mode work with neovim 0.0.1 (which I think you're using), why don't you pull the most recent changes and try again. Let me know how it goes.

**Comment by caiocutrim** [comment]
I'm using the 0.1.0-dev version, so I need to downgrade to using your project...

**Comment by caiocutrim** [comment]
I can't found this old version...

**Comment by caiocutrim** [comment]
It not works...

**Comment by carlosdcastillo** [comment]
Can you say more about what error you're seeing.

**Comment by carlosdcastillo** [comment]
I'm using this version: https://github.com/neovim/neovim/archive/v0.1.0.tar.gz

**Comment by caiocutrim** [comment]
the keyboard not works, not type anything, I'm put the DEBUG=true, so was this message has open...

**Comment by caiocutrim** [comment]
something now works here XD, I don't what is going on lol
