### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by larsks** [carlosdcastillo/vim-mode#37]
This sounds like a neat idea!  I tried running this with atom atom-1.4.3-0.1.fc21.x86_64 and it fails with:

```
Uncaught TypeError: Invalid Point: (NaN, 0)
```

With the follow stacktrace:

```
TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at MarkerLayer.module.exports.MarkerLayer.setMarkerRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:381:29)
    at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:321:20)
    at Marker.module.exports.Marker.setHeadPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:135:19)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadBufferPosition (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:175:32)
    at /usr/share/atom/resources/app.asar/src/cursor.js:82:31
    at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app.asar/src/cursor.js:673:7)
    at Cursor.module.exports.Cursor.setBufferPosition (/usr/share/atom/resources/app.asar/src/cursor.js:80:19)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:1415:23
    at TextEditor.module.exports.TextEditor.moveCursors (/usr/share/atom/resources/app.asar/src/text-editor.js:1652:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1414:19)
    at VimState.module.exports.VimState.redraw_screen (/home/lars/.atom/packages/nvim-mode/lib/vim-state.coffee:978:47)
    at VimState.redraw_screen (/home/lars/.atom/packages/nvim-mode/lib/vim-state.coffee:1:1)
    at EventHandler.handleEvent (/home/lars/.atom/packages/nvim-mode/lib/vim-state.coffee:725:19)
    at Session.<anonymous> (/home/lars/.atom/packages/nvim-mode/lib/vim-state.coffee:1:1)
    at emitTwo (events.js:87:13)
    at Session.emit (events.js:172:7)
    at Session._parse_message (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/index.js:101:10)
    at Decoder.<anonymous> (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/index.js:42:11)
    at emitOne (events.js:77:13)
    at Decoder.emit (events.js:169:7)
    at readableAddChunk (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Decoder.Readable.push (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Decoder.Transform.push (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:80:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.decodeWithoutHeader [as _transform] (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:91:10)
    at Decoder.Transform._read (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Decoder.Transform._write (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Decoder.Writable.write (/home/lars/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by GeorgeTG** [comment]
Same here.
