### ISSUE TITLE
Atom 1.9.5 support?

### ISSUE THREAD

**Issue by junwatu** [carlosdcastillo/vim-mode#42]
Failed to load the atom-neovim package on Atom 1.9.5  and neovim 1.5.0

```
At list argument must be an Array of Buffers

TypeError: list argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:321:13)
    at BufferList.copy (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/bl/bl.js:118:21)
    at BufferList.slice (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/bl/bl.js:93:15)
    at Object.encode (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/index.js:188:18)
    at Encoder._transform (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/lib/streams.js:37:25)
    at Encoder.Transform._read (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Encoder.Transform._write (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Encoder.Writable.write (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Session.request (/home/equan/.atom/packages/nvim-mode/node_modules/msgpack5rpc/index.js:68:17)
    at Object.<anonymous> (/home/equan/.atom/packages/vim-mode/lib/vim-state.coffee:77:12)
    at Object.<anonymous> (/home/equan/.atom/packages/vim-mode/lib/vim-state.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/equan/.atom/packages/vim-mode/lib/vim-mode.coffee:4:12)
    at Object.<anonymous> (/home/equan/.atom/packages/vim-mode/lib/vim-mode.coffee:2:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
```

**Comment by richardmon** [comment]
+1

**Comment by gavsim** [comment]
+1

**Comment by samhstn** [comment]
This solution may not work for you, but I mine was broken because I was not using the master branch version. I fixed it with the following:

`cd ~/.atom/packages/vim-mode`

Then, check if you are on the master branch `git branch`, if not checkout to master and pull

Then, in atom settings `cmd + ,`

Open the vim-mode settings by clicking on the vim-mode package and you may have a message saying the package is out of date, then click the option to update it.

It may not help, but worth checking just in case

**Comment by harindu95** [comment]
You can change the msgpack5rc version to 1.0.2 in package.json. It worked for me. 
https://github.com/harindu95/vim-mode

**Comment by sollidsnake** [comment]
@harindu95 thanks, that does seem to solve the error. But then there's another issue. When typing into atom buffer, the neovim buffer receives the keys, but in atom it's always empty.

**Comment by harindu95** [comment]
@sollidsnake I think there is a syncing issue. When I tried it out, it seems to sync sometimes when saving. Otherwise the output on atom was messed up.
